# Pytorch Dataset

    - 대용량의 데이터를 어떤 구조로 모델에 잘 먹여줄(feeding)것인가 

class Dataset    
:  데이터의 입력형태를 정의하는 클래스 

In [1]:
import torch
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, text, labels):
        self.labels = labels
        self.data = text
    
    # 데이터의 전체 길이 return 
    def __len__(self):
        return len(self.labels)
    
    # index를 주었을때 (x,y)형태로 데이터 반환 
    def __getitem__(self, idx):
        label = self.labels[idx]
        text = self.data[idx]
        sample = {"Text": text, "Class" : label}
        return sample

In [4]:
text = ['Happy', 'Amazing', 'Sad', "Unhappy", "Glum"]
labels = ['Positive', 'Positive', 'Negative', 'Negative', 'Negative']
MyDataset = CustomDataset(text,labels)

In [10]:
text, labels

(['Happy', 'Amazing', 'Sad', 'Unhappy', 'Glum'],
 ['Positive', 'Positive', 'Negative', 'Negative', 'Negative'])

class DataLoader   
: Data의 Batch를 생성해주는 class 

In [19]:
# DataLoader(dataset, batch_size=, shuffle=bool, sampler=None
#            , ... num_workers, collate_fn=None )

# collate fn 
# : [[data, label],[data,label]] -> [data][label]
#                                   [data][label]

In [25]:
from torch.utils.data import DataLoader

MyDataLoader = DataLoader(MyDataset, batch_size=2,shuffle=True)

for dataset in MyDataLoader:
    print(dataset)

{'Text': ['Sad', 'Happy'], 'Class': ['Negative', 'Positive']}
{'Text': ['Amazing', 'Glum'], 'Class': ['Positive', 'Negative']}
{'Text': ['Unhappy'], 'Class': ['Negative']}


In [46]:
# collate fn 

class ExampleDataset(Dataset):
    def __init__(self,num):
        self.num = num
    
    def __len__(self):
        return self.num
    
    def __getitem__(self,idx):
        return {"X": torch.tensor([idx]*(idx+1), dtype=torch.float32),
               "y":torch.tensor(idx,dtype=torch.float32)}
    
    
    
dataset_example = ExampleDataset(num=10)
dataloader_example = torch.utils.data.DataLoader(dataset_example, batch_size=1)

In [47]:
next(iter(dataset_example))

{'X': tensor([0.]), 'y': tensor(0.)}

In [48]:
for i in dataloader_example:
    print(i["X"])

tensor([[0.]])
tensor([[1., 1.]])
tensor([[2., 2., 2.]])
tensor([[3., 3., 3., 3.]])
tensor([[4., 4., 4., 4., 4.]])
tensor([[5., 5., 5., 5., 5., 5.]])
tensor([[6., 6., 6., 6., 6., 6., 6.]])
tensor([[7., 7., 7., 7., 7., 7., 7., 7.]])
tensor([[8., 8., 8., 8., 8., 8., 8., 8., 8.]])
tensor([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])
