In [1]:
import torch

# autograd & optimizer


In [ ]:
# torch.nn.Module

# input / output / Forward / Backward

# 학습의 대상이되는 parameter(tensor)정의

# nn.Parameter
# - tensor의 상속객체 

In [199]:
import torch
from torch import nn
from torch import Tensor

In [204]:
class MyLinear (nn.Module):
    def __init__(self, in_features, out_features, bias=True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        
        self.weights = nn.Parameter(
            torch.randn(in_features, out_features))
        self.bias = nn.Parameter(torch.randn(out_features))
    
    def forward(self, x: Tensor):
        return x @ self.weights + self.bias

In [205]:
x = torch.randn(5,7)
x

tensor([[ 0.3896,  1.1459, -0.0348, -1.5924,  0.4654, -0.1913, -0.5877],
        [ 0.3763,  0.6942, -1.8856, -1.8911, -1.2746, -1.9195, -1.3673],
        [ 0.9060,  1.0741, -2.2453, -1.3985, -0.2711,  0.7508, -0.3743],
        [ 0.7015, -0.4305, -0.8190,  1.5281, -0.7773, -0.4323,  1.2546],
        [ 1.0900, -0.4190,  0.0659, -1.5090, -1.5751,  0.3330,  0.0050]])

In [206]:
a = MyLinear(7,3)
a.forward(x)

tensor([[-2.3379, -4.3404,  4.3791],
        [-4.5275, -0.9921,  3.7437],
        [-2.5923, -1.3030,  0.6212],
        [ 0.7383,  1.2610, -2.4558],
        [ 0.4386, -3.1067, -0.5780]], grad_fn=<AddBackward0>)

In [211]:
from torch.autograd import Variable

class LinearLayer(nn.Module):
    def __init__(self, in_features, out_features, bias=True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weights = nn.Parameter(torch.randn(in_features,out_features))
        self.bias = nn.Parameter(torch.randn(out_features))
    
    def forward(self, x:Tensor):
        x = x @ self.weights + self.bias
        return x

In [212]:
a = LinearLayer(3,5)
a.weights, a.bias

x = torch.randn(7,3)
a.forward(x)


tensor([[ 1.9874,  5.6381,  0.2759,  1.9646, -3.6695],
        [-2.7893, -3.0407,  2.5097, -3.7958,  0.5242],
        [ 0.1104,  0.9346,  0.7894, -0.5881, -0.5484],
        [ 2.1674,  3.5793,  0.9341, -1.0308, -4.6447],
        [-1.3322,  0.5629,  0.7290,  0.7674,  1.5763],
        [ 0.6718,  0.2515, -0.1364,  0.0555,  1.3575],
        [ 2.4978,  1.3639, -0.4062, -0.5186, -0.7460]], grad_fn=<AddBackward0>)

In [222]:
import numpy as np

x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1,1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1,1)

In [223]:
x_train, y_train

(array([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], dtype=float32),
 array([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.],
        [15.],
        [17.],
        [19.],
        [21.]], dtype=float32))

In [215]:
from torch.autograd import Variable

class LinearRegression(torch.nn.Module):
    def __init__(self,inputSize,outputSize):
        super().__init__()
        self.linear = torch.nn.Linear(inputSize, outputSize)
    
    def forward(self,x):
        out = self.linear(x)
        return out 

In [216]:
inputDim = 1
outputDim = 1
learningRate = 0.01
epochs = 100

model = LinearRegression(inputDim, outputDim)

# cuda 
if torch.cuda.is_available():
    model.cuda()

In [218]:
# loss func and optim 
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learningRate)

In [233]:
# input example
Variable(torch.from_numpy(x_train).cuda())

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], device='cuda:0')

In [226]:
for epoch in range(epochs):
    
    inputs = Variable(torch.from_numpy(x_train).cuda())
    labels = Variable(torch.from_numpy(y_train).cuda())
    
    # each epoch , gradient 초기화 
    optimizer.zero_grad()
    
    # Forward : get output from the model, given the input 
    # model = LinearRegression(inputDim, outputDim)
    outputs = model(inputs) # y-hat
    
    # calculate MSE loss 
    loss = criterion(outputs, labels)
    print(loss)
    
    # get gradient w, r, t to parameters 
    loss.backward()
    
    
    # update parameters 
    optimizer.step()
    
    print("epoch: {}, loss: {}".format(epoch,loss.item()))

tensor(0.0490, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 0, loss: 0.0489596463739872
tensor(0.0484, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 1, loss: 0.04841294884681702
tensor(0.0479, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 2, loss: 0.04787225276231766
tensor(0.0473, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 3, loss: 0.047337744385004044
tensor(0.0468, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 4, loss: 0.04680907353758812
tensor(0.0463, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 5, loss: 0.046286385506391525
tensor(0.0458, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 6, loss: 0.04576951265335083
tensor(0.0453, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 7, loss: 0.045258451253175735
tensor(0.0448, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 8, loss: 0.04475307837128639
tensor(0.0443, device='cuda:0', grad_fn=<MseLossBackward>)
epoch: 9, loss: 0.04425327852368355
tensor(0.0438, device='cuda:0', grad_fn=<MseLoss

## Logistic Regression


In [281]:
device = torch.device('cuda:0')


class LogisticRegression(nn.Module):
    def __init__(self, dim, lr = torch.scalar_tensor(0.01)):
        super(LogisticRegression,self).__init__()
        
        self.weights = torch.zeros(dim, 1, dtype = torch.float).to(device)
        self.bias = torch.scalar_tensor(0).to(device)
        self.grads = {"dw": torch.zeros(dim,1,dtype=torch.float).to(device),
                     "db": torch.scalar_tensor(0).to(device)}
        self.lr = lr.to(device)
    
    # sigmoid 정의 
    def sigmoid(self,z):
        return 1 / (1+torch.exp(-z))
    
    # forward
    def forward(self,x):
        z = torch.mm(self.weights.T,x)
        a = self.sigmoid(z)
        return a 
    
    def backward(self,x,yhat,y):
        self.grads["dw"] = (1/x.shape[1]) * torch.mm(x,(yhat-y).T)
        self.grads['db'] = (1/x.shape[1]) * torch.sum(yhat-y)
        
    def optimize(self):
        self.weights = self.weights - self.lr* self.grads['dw']
        self.bias = self.bias - self.lr * self.grads['db']
    
    
 
    
# loss function    
def loss(yhat, y):
    m = y.size()[1]
    return -(1/m) * torch.sum(y*torch.log(yhat) + (1-y) * torch.log(1-yhat))

# prediction 
def predict(yhat, y):
    y_pred = torch.zeros(1, y.size()[1])
    for i in range(yhat.size()[1]):
        if yhat[0,i] <= 0.5:
            y_pred[0,i] = 0
        else:
            y_pred[0,i] = 1
    return 100 - torch.mean(torch.abs(y_pred - y)) * 100

In [286]:
model = LogisticRegression(3)
model.to(device)
model.optimize()

In [236]:
torch.scalar_tensor(0.01)

tensor(0.0100)

In [239]:
torch.mm(torch.randn(3,3), torch.randn(3,1))

tensor([[0.1712],
        [4.3063],
        [0.1323]])

In [271]:
z = torch.zeros(3,1,dtype=torch.float)
z.T

tensor([[0., 0., 0.]])