<a href="https://colab.research.google.com/github/tommyEzreal/study_low_level/blob/main/pytorch/%EB%AA%A8%EB%91%90%EB%A5%BC%EC%9C%84%ED%95%9C%EB%94%A5%EB%9F%AC%EB%8B%9D2/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim 

In [3]:
# seed 고정
torch.manual_seed(0)

In [41]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
print(x_train.shape, y_train.shape)
print()
print("x_train:",x_train)
print("y_train:",y_train)

torch.Size([3, 1]) torch.Size([3, 1])

x_train: tensor([[1.],
        [2.],
        [3.]])
y_train: tensor([[2.],
        [4.],
        [6.]])


In [42]:
# weight, bias default 
# requires_grad = define as a variable, trained argument 

W = torch.zeros(1, requires_grad = True)
print("w default:",W)

print()

b = torch.zeros(1, requires_grad=True)
print("b default:",b)

w default: tensor([0.], requires_grad=True)

b default: tensor([0.], requires_grad=True)


In [43]:
# hypothesis 

# y = Wx + b fits the data  H(x)

h = x_train * W + b 
print("hypothesis:",h)

hypothesis: tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [44]:
# define cost function 

cost = torch.mean((h - y_train) ** 2) 
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [45]:
# gradient descent

# using SGD, learning rate = 0.01 
optimizer = torch.optim.SGD([W,b], lr=0.01)

# default grad 
optimizer.zero_grad()

# calculate grad 
cost.backward()

# update Weight and bias 
optimizer.step()

In [46]:
W, b 

(tensor([0.1867], requires_grad=True), tensor([0.0800], requires_grad=True))

In [47]:
# per epoch 

epochs = 1000 

for epoch in range(epochs + 1):
  h = x_train * W + b 
  cost = torch.mean((h-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # logging per 10 step 
  if epoch % 100 == 0:
    print('Epoch: {:4d}/{}, W: {:.3f}, b:{:.3f}, cost: {:.6f}'.format(
        epoch,epochs,W.item(),b.item(),cost.item())) 

Epoch    0/1000, W: 0.353, b:0.151, cost: 14.770963
Epoch  100/1000, W: 1.746, b:0.577, cost: 0.047939
Epoch  200/1000, W: 1.801, b:0.453, cost: 0.029624
Epoch  300/1000, W: 1.843, b:0.356, cost: 0.018306
Epoch  400/1000, W: 1.877, b:0.280, cost: 0.011312
Epoch  500/1000, W: 1.903, b:0.220, cost: 0.006990
Epoch  600/1000, W: 1.924, b:0.173, cost: 0.004319
Epoch  700/1000, W: 1.940, b:0.136, cost: 0.002669
Epoch  800/1000, W: 1.953, b:0.107, cost: 0.001649
Epoch  900/1000, W: 1.963, b:0.084, cost: 0.001019
Epoch 1000/1000, W: 1.971, b:0.066, cost: 0.000630


### 다중연산 

In [21]:
# compute with matrix

x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [5]:
x_train.shape, y_train.shape

(torch.Size([5, 3]), torch.Size([5, 1]))

In [22]:
# weight and bias - 3 weight, bias default 

W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)
W.shape, b.shape

(torch.Size([3, 1]), torch.Size([1]))

In [23]:
# matrix multiplication으로 한번에 h 정의 
h = x_train.matmul(W) + b 

In [19]:
h.squeeze().detach()

tensor([0., 0., 0., 0., 0.])

In [26]:
# optimizer

optimizer = optim.SGD([W,b], lr=1e-5)

# loop 

epochs = 20 

for epoch in range(epochs+1):

  h = x_train.matmul(W) + b
  
  cost = torch.mean((h-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # .detach() - stop grad propagation 
  print("Epoch: {:4d}/{} h: {}, cost: {:.6f}".format(
      epoch, epochs, h.squeeze().detach(), cost.item()
  ))

Epoch:    0/20 h: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]), cost: 9537.694336
Epoch:    1/20 h: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]), cost: 3069.590088
Epoch:    2/20 h: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]), cost: 990.670288
Epoch:    3/20 h: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]), cost: 322.481873
Epoch:    4/20 h: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]), cost: 107.717064
Epoch:    5/20 h: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]), cost: 38.687496
Epoch:    6/20 h: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]), cost: 16.499043
Epoch:    7/20 h: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]), cost: 9.365656
Epoch:    8/20 h: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]), cost: 7.071114
Epoch:    9/20 h: tensor([153.5285, 184.4835, 175.1338, 197.9415, 140.7325]), cost: 6.331847
Epoch:   10/20 h: tensor([153.7572, 184.7582, 175.3958, 198.2

## nn.Module 활용 

In [29]:
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(0)

In [30]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [37]:
model = nn.Linear(1,1) # (output_dim, input_dim)
model

Linear(in_features=1, out_features=1, bias=True)

In [112]:
# check parameters
# W & b 
# print(list(model.parameters()))

# for param in model.parameters():
#   print(param.data.squeeze().detach())

list(i.detach() for i in model.parameters())[0]


tensor([[1.9996]])

In [123]:
# optimizer

optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

# training loop 

epochs = 1000
for epoch in range(epochs):

  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train) 

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print("Epoch:{:4d}/{}, W&b:{}, cost: {:.6f}".format(
        epoch, epochs, list(i.detach() for i in model.parameters()) ,cost.item()
    ))

Epoch:   0/1000, W&b:[tensor([[288.7074, 288.5964, 291.3774]]), tensor([2.9926])], cost: 28581.875000
Epoch: 100/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 200/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 300/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 400/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 500/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 600/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 700/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 800/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan
Epoch: 900/1000, W&b:[tensor([[nan, nan, nan]]), tensor([nan])], cost: nan


In [40]:
new_var = torch.FloatTensor([[4]])
pred_y = model(new_var) 

print(pred_y)

tensor([[7.9994]], grad_fn=<AddmmBackward0>)


### with matrix multiplication

In [126]:
# with matrix multiplication 

# data
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


# model
model = nn.Linear(3,1) # 3features, 1output 

#check parameters
print("params:",list(param.detach() for param in model.parameters()))

# opitimizer 
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

# training loop 
epochs = 1000

for epoch in range(epochs+1):

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print("Epoch: {:4d}/{}, W&b: {}, cost: {}".format(
        epoch, epochs, list(params.detach() for params in model.parameters()), cost.item()
    ))



params: [tensor([[0.4963, 0.2576, 0.2798]]), tensor([0.0304])]
Epoch:    0/1000, W&b: [tensor([[0.6392, 0.4003, 0.4244]]), tensor([0.0320])], cost: 7008.5478515625
Epoch:  100/1000, W&b: [tensor([[0.8239, 0.5788, 0.6084]]), tensor([0.0342])], cost: 0.5722898244857788
Epoch:  200/1000, W&b: [tensor([[0.8268, 0.5757, 0.6086]]), tensor([0.0344])], cost: 0.5544425249099731
Epoch:  300/1000, W&b: [tensor([[0.8296, 0.5727, 0.6088]]), tensor([0.0345])], cost: 0.5375221371650696
Epoch:  400/1000, W&b: [tensor([[0.8324, 0.5698, 0.6089]]), tensor([0.0346])], cost: 0.5214717984199524
Epoch:  500/1000, W&b: [tensor([[0.8351, 0.5670, 0.6090]]), tensor([0.0347])], cost: 0.5062476992607117
Epoch:  600/1000, W&b: [tensor([[0.8377, 0.5642, 0.6091]]), tensor([0.0348])], cost: 0.4918190836906433
Epoch:  700/1000, W&b: [tensor([[0.8403, 0.5616, 0.6092]]), tensor([0.0349])], cost: 0.47812825441360474
Epoch:  800/1000, W&b: [tensor([[0.8428, 0.5590, 0.6093]]), tensor([0.0350])], cost: 0.4651438295841217
Epo