<a href="https://colab.research.google.com/github/tommyEzreal/study_low_level/blob/main/pytorch/%EB%AA%A8%EB%91%90%EB%A5%BC%EC%9C%84%ED%95%9C%EB%94%A5%EB%9F%AC%EB%8B%9D2/RNN_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Recurrent NN for sequential data 

In [1]:
# rnn = torch.nn.RNN(input_size, hidden_size) -> cell 
# hidden_size = ouput_size
# cause its recursive! 

# outputs, _status = rnn(input_data) -> Xt to ht 

# inputs,outputs shape(batch, sequence_len, hidden_size)

In [1]:
import torch
import numpy as np

In [2]:
# ex



input_size = 4
hidden_size = 2

h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

# sequence length
input_data_np = np.array([[h,e,l,l,o],
                          [e,o,l,l,l],
                          [l,l,e,e,l]], dtype = np.float32)
# into tensor 
input_data = torch.Tensor(input_data_np)

rnn = torch.nn.RNN(input_size, hidden_size)

outputs, _status = rnn(input_data)


In [4]:
input_data, input_data.shape

(tensor([[[1., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          [0., 0., 0., 1.]],
 
         [[0., 1., 0., 0.],
          [0., 0., 0., 1.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.]],
 
         [[0., 0., 1., 0.],
          [0., 0., 1., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.]]]), torch.Size([3, 5, 4]))

In [5]:
rnn

RNN(4, 2)

In [38]:
outputs, outputs.shape
outputs.view(-1,5), outputs

(tensor([[ 0.8761, -0.4885,  0.8634, -0.8222,  0.5359],
         [-0.9321,  0.5359, -0.9321,  0.8474, -0.8229],
         [ 0.8200, -0.7071,  0.8347, -0.7416,  0.6045],
         [-0.9254,  0.6045, -0.9254,  0.5084, -0.8995],
         [ 0.4888, -0.8974,  0.4930, -0.8975,  0.8816],
         [-0.7945,  0.8816, -0.7945,  0.6042, -0.9261]],
        grad_fn=<ViewBackward0>), tensor([[[ 0.8761, -0.4885],
          [ 0.8634, -0.8222],
          [ 0.5359, -0.9321],
          [ 0.5359, -0.9321],
          [ 0.8474, -0.8229]],
 
         [[ 0.8200, -0.7071],
          [ 0.8347, -0.7416],
          [ 0.6045, -0.9254],
          [ 0.6045, -0.9254],
          [ 0.5084, -0.8995]],
 
         [[ 0.4888, -0.8974],
          [ 0.4930, -0.8975],
          [ 0.8816, -0.7945],
          [ 0.8816, -0.7945],
          [ 0.6042, -0.9261]]], grad_fn=<StackBackward0>))

In [11]:
_status, _status.shape

(tensor([[[ 0.4888, -0.8974],
          [ 0.4930, -0.8975],
          [ 0.8816, -0.7945],
          [ 0.8816, -0.7945],
          [ 0.6042, -0.9261]]], grad_fn=<StackBackward0>),
 torch.Size([1, 5, 2]))

HIHELLO problem

  - H -> I or E / L -> L or O 

In [129]:
# hihello 
char_set = ['h','i','e','l','o']

input_size = len(char_set)
hidden_size = len(char_set)

learning_rate = 0.1

# data setting
x_data = [[0, 1, 0, 2, 3, 3]] # 'hihell'
x_one_hot = [[[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [1, 0, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0]]]
y_data = [[1, 0, 2, 3, 3, 4]] #'ihello'

X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)



In [130]:
print(input_size, hidden_size)


5 5


In [131]:
rnn = torch.nn.RNN(input_size, hidden_size, batch_first=True) # order of output (batch, sequence, hidden)

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(rnn.parameters(), lr = learning_rate)

# training loop 

for i in range(10):
  print()
  outputs, _status = rnn(X)
  loss = criterion(outputs.view(-1, input_size), Y.view(-1)) # to calculate loss, 각각 펴주기 
  print(outputs)
  # loss = criterion(outputs, Y) 
  print("outputs:", outputs)
  print("outputs.view:", outputs.view(-1,input_size))
  print("Y:",Y)
  print("loss:",loss)
  print()
  
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  result = outputs.data.numpy().argmax(axis=2) # which char 
  print("outputs.argmax:",result)
  
  result_str = ''.join([char_set[c] for c in np.squeeze(result)])
  print()
  print(i, "loss: ", loss.item(), "prediction: ", result, "true Y: ", y_data, "prediction str: ", result_str)


tensor([[[ 0.2770,  0.1169, -0.0729, -0.3415,  0.6787],
         [ 0.4236,  0.2219,  0.5266, -0.3019,  0.9032],
         [ 0.4988,  0.5893, -0.1510, -0.5917,  0.7987],
         [ 0.6098,  0.4229,  0.3366, -0.2880,  0.9209],
         [ 0.7367,  0.6163, -0.0034, -0.4871,  0.7860],
         [ 0.7812,  0.4667,  0.0476, -0.2591,  0.8322]]],
       grad_fn=<TransposeBackward1>)
outputs: tensor([[[ 0.2770,  0.1169, -0.0729, -0.3415,  0.6787],
         [ 0.4236,  0.2219,  0.5266, -0.3019,  0.9032],
         [ 0.4988,  0.5893, -0.1510, -0.5917,  0.7987],
         [ 0.6098,  0.4229,  0.3366, -0.2880,  0.9209],
         [ 0.7367,  0.6163, -0.0034, -0.4871,  0.7860],
         [ 0.7812,  0.4667,  0.0476, -0.2591,  0.8322]]],
       grad_fn=<TransposeBackward1>)
outputs.view: tensor([[ 0.2770,  0.1169, -0.0729, -0.3415,  0.6787],
        [ 0.4236,  0.2219,  0.5266, -0.3019,  0.9032],
        [ 0.4988,  0.5893, -0.1510, -0.5917,  0.7987],
        [ 0.6098,  0.4229,  0.3366, -0.2880,  0.9209],
      

another example (appl -> pple)
- use nn.module & fc layer

In [10]:
input_str = 'appl'
label_str = 'pple'

char_vocab = sorted(list(set(input_str+label_str)))
vocab_size = len(char_vocab)
print('size of vocab: {}'.format(vocab_size))

size of vocab: 4


In [12]:
# params 
input_size = vocab_size
hidden_size = 4
output_size = 4
learning_rate = 0.1

In [15]:
# vocab int indexing 
char_to_index = dict((c,i) for i,c in enumerate(char_vocab))
char_to_index

{'a': 0, 'e': 1, 'l': 2, 'p': 3}

In [27]:
# decoding 
index_to_char = {}
for key, value in char_to_index.items():
  print(key, value)
  index_to_char[value] = key

print(index_to_char)

a 0
e 1
l 2
p 3
{0: 'a', 1: 'e', 2: 'l', 3: 'p'}


In [60]:
# int encoding 

x_data = [char_to_index[c] for c in input_str]
y_data = [char_to_index[c] for c in label_str]

print("appl:",x_data)
print("pple:",y_data)

appl: [0, 3, 3, 2]
pple: [3, 3, 2, 1]


In [61]:
# into tensor 
x_data = torch.LongTensor(x_data)
x_data.unsqueeze_(0)

y_data = torch.LongTensor(y_data)
y_data.unsqueeze_(0)

print(x_data, y_data)

tensor([[0, 3, 3, 2]]) tensor([[3, 3, 2, 1]])


In [63]:
# into one-hot vec 

# identitiy matrix 만들고 각 index별로 vec에 값 넣어주기 
x_one_hot = [np.eye(vocab_size)[x] for x in x_data]
x_one_hot

[array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]])]

In [83]:
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)
X,Y

(tensor([[[1., 0., 0., 0.],
          [0., 0., 0., 1.],
          [0., 0., 0., 1.],
          [0., 0., 1., 0.]]]), tensor([[3, 3, 2, 1]]))

In [82]:
print("x_train:", X.shape)
print("Y_label:", Y.shape)

x_train: torch.Size([1, 4, 4])
Y_label: torch.Size([1, 4])


In [89]:
class MyRNN(torch.nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(MyRNN, self).__init__()
    self.rnn = torch.nn.RNN(input_size, hidden_size, batch_first = True)
    self.fc = torch.nn.Linear(hidden_size, output_size, bias=True)

  def forward(self, x):
    x, _status = self.rnn(x)
    x = self.fc(x)
    return x

In [91]:
rnn = MyRNN(input_size, hidden_size, output_size)

In [93]:
outputs = rnn(X)
print(outputs.shape) # batch, timestep, hiddensize
print(outputs)

torch.Size([1, 4, 4])
tensor([[[-0.0111,  0.2383, -0.6279, -0.1686],
         [-0.3355,  0.3806, -0.9105, -0.7137],
         [-0.2286,  0.3014, -0.7540, -0.7822],
         [-0.5405,  0.2158, -1.1611, -0.5715]]], grad_fn=<ViewBackward0>)


In [96]:
outputs.view(-1, input_size) , Y.view(-1)

(tensor([[-0.0111,  0.2383, -0.6279, -0.1686],
         [-0.3355,  0.3806, -0.9105, -0.7137],
         [-0.2286,  0.3014, -0.7540, -0.7822],
         [-0.5405,  0.2158, -1.1611, -0.5715]], grad_fn=<ViewBackward0>),
 tensor([3, 3, 2, 1]))

In [98]:
# loss and optim 

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(rnn.parameters(), lr = learning_rate)

In [101]:
# training loop

for i in range(10):
  outputs = rnn(X)
  loss = criterion(outputs.view(-1, input_size), Y.view(-1))

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  result = outputs.data.numpy().argmax(axis=2)
  #decoding
  result_str = ''.join( [index_to_char[c] for c in np.squeeze(result)] )

  print("epoch: {} , loss: {} , pred: {} , trueY : {} , pred_str: {}".format(
      i, loss.item(), result, y_data, result_str
  ))

epoch: 0 , loss: 1.487595558166504 , pred: [[1 1 1 1]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: eeee
epoch: 1 , loss: 1.254179835319519 , pred: [[3 1 1 1]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: peee
epoch: 2 , loss: 1.0970252752304077 , pred: [[3 3 1 3]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: ppep
epoch: 3 , loss: 0.9141278266906738 , pred: [[3 3 3 3]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: pppp
epoch: 4 , loss: 0.7242991328239441 , pred: [[3 3 2 3]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: pplp
epoch: 5 , loss: 0.5651026964187622 , pred: [[3 3 2 1]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: pple
epoch: 6 , loss: 0.42908716201782227 , pred: [[3 3 2 1]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: pple
epoch: 7 , loss: 0.31297120451927185 , pred: [[3 3 2 1]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: pple
epoch: 8 , loss: 0.2254246026277542 , pred: [[3 3 2 1]] , trueY : tensor([[3, 3, 2, 1]]) , pred_str: pple
epoch: 9 , loss: 0.16333362460136414 , pred: [

In [100]:
''.join(['iel'])

'iel'

long sequence dataset

In [125]:
# character sequence
sample = 'if you want you'

# make dict 
char_set = list(set(sample))
print("char_set:",char_set)

char_dic = {c: i for i, c in enumerate(char_set)}
print("char_dic:",char_dic)

# parms
dic_size = len(char_dic)
hidden_size = len(char_dic)
learning_rate = 0.1
print(len(char_dic))
# data setting 

sample_idx = [char_dic[c] for c in sample]
print("sample_idx:", sample_idx)

x_data = [sample_idx[:-1]]
x_one_hot = [np.eye(dic_size)[x] for x in x_data] # np.eye -> into identity M 
y_data = [sample_idx[1:]]

X = torch.FloatTensor(x_data)
Y = torch.LongTensor(y_data)
print()
print("x_data:", x_data)
print("y_data:", y_data)

print()
print(X)
print(Y)

char_set: ['y', 'w', 't', 'f', 'a', 'i', 'n', 'u', ' ', 'o']
char_dic: {'y': 0, 'w': 1, 't': 2, 'f': 3, 'a': 4, 'i': 5, 'n': 6, 'u': 7, ' ': 8, 'o': 9}
10
sample_idx: [5, 3, 8, 0, 9, 7, 8, 1, 4, 6, 2, 8, 0, 9, 7]

x_data: [[5, 3, 8, 0, 9, 7, 8, 1, 4, 6, 2, 8, 0, 9]]
y_data: [[3, 8, 0, 9, 7, 8, 1, 4, 6, 2, 8, 0, 9, 7]]

tensor([[5., 3., 8., 0., 9., 7., 8., 1., 4., 6., 2., 8., 0., 9.]])
tensor([[3, 8, 0, 9, 7, 8, 1, 4, 6, 2, 8, 0, 9, 7]])


In [197]:
sentence = ("if you want to build a ship, don't drum up people together to "
            "collect wood and don't assign them tasks and work, but rather "
            "teach them to long for the endless immensity of the sea.")

char_set = list(set(sentence))
char_dic = {c: i for i,c in enumerate(char_set)}
char_dic

{'l': 0,
 'm': 1,
 'h': 2,
 'i': 3,
 't': 4,
 'r': 5,
 'y': 6,
 'u': 7,
 "'": 8,
 's': 9,
 '.': 10,
 'o': 11,
 'c': 12,
 'a': 13,
 'd': 14,
 'b': 15,
 'n': 16,
 'g': 17,
 'p': 18,
 ' ': 19,
 'w': 20,
 'k': 21,
 ',': 22,
 'e': 23,
 'f': 24}

In [217]:
dic_size = len(char_dic)

# params
input_size = dic_size
hidden_size = dic_size
seq_len = 10
learning_rate=0.1

In [202]:
x_data = []
y_data = []

for i in range(0, len(sentence) - seq_len): # 가져오는 chunk의 개수 
  x_str = sentence[i:i+ seq_len] # if you wan
  y_str = sentence[i+1 : i+ seq_len+1] # f you want
  print(i , x_str, "->", y_str)

  # int encoding
  x_data.append([char_dic[c] for c in x_str])
  y_data.append([char_dic[c] for c in y_str])

x_one_hot = [np.eye(dic_size)[x] for x in x_data] # dicsize만큼 onehot matrix 

X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

0 if you wan -> f you want
1 f you want ->  you want 
2  you want  -> you want t
3 you want t -> ou want to
4 ou want to -> u want to 
5 u want to  ->  want to b
6  want to b -> want to bu
7 want to bu -> ant to bui
8 ant to bui -> nt to buil
9 nt to buil -> t to build
10 t to build ->  to build 
11  to build  -> to build a
12 to build a -> o build a 
13 o build a  ->  build a s
14  build a s -> build a sh
15 build a sh -> uild a shi
16 uild a shi -> ild a ship
17 ild a ship -> ld a ship,
18 ld a ship, -> d a ship, 
19 d a ship,  ->  a ship, d
20  a ship, d -> a ship, do
21 a ship, do ->  ship, don
22  ship, don -> ship, don'
23 ship, don' -> hip, don't
24 hip, don't -> ip, don't 
25 ip, don't  -> p, don't d
26 p, don't d -> , don't dr
27 , don't dr ->  don't dru
28  don't dru -> don't drum
29 don't drum -> on't drum 
30 on't drum  -> n't drum u
31 n't drum u -> 't drum up
32 't drum up -> t drum up 
33 t drum up  ->  drum up p
34  drum up p -> drum up pe
35 drum up pe -> rum up peo
36

In [211]:
X.shape, Y.shape

(torch.Size([170, 10, 25]), torch.Size([170, 10]))

In [213]:
X[0], Y[0]

(tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.

In [209]:
# add fc layer 

class MyRNN(torch.nn.Module):
  def __init__(self, input_size, hidden_size, layers):
    super(MyRNN, self).__init__()
    self.rnn = torch.nn.RNN(input_size, hidden_size,
                            num_layers=layers,
                            batch_first = True)
    self.fc = torch.nn.Linear(hidden_size, hidden_size, bias=True)
  
  def forward(self, x):
    output, _status = self.rnn(x)
    output = self.fc(output)
    return output

In [216]:
rnn = MyRNN(input_size = dic_size, hidden_size = hidden_size, layers=2)

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(rnn.parameters(), lr = learning_rate)

outputs = rnn(X)
outputs.shape

torch.Size([170, 10, 25])

In [220]:
for i in range(1000):
  outputs = rnn(X)
  loss = criterion(outputs.view(-1, input_size), Y.view(-1))

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  results = outputs.argmax(dim=2)
  predict_str = ""
  for j, result in enumerate(results):
    if j ==0:
      predict_str += ''.join([char_set[t] for t in result])
    else:
      predict_str += char_set[result[-1]]
  
  print(predict_str)


g, oglwonm woecos , ant ite ton't eoim toecan te toilth m to to 'tns woid and ton't assiim toem tonss anm tonl, t t woshem to so them to ton'econ toem sdeessiid  as ty an tyem ost
g, o  wonm wo con , a t it, ton't aoum to cen  e to  ch m to co 'ens aond ans to 't ansiim toem tonss anm tos , t t euthem to ss them to con'econ them n  essiit   s ty an toemesst
g, o  wonm to duie, antoit, lon't eoum tr ben  e to  th m to do 'ent aond and to ', ensium'them tonks anm tos , tut euthem to cs them to 'on'elos them nd ess ig   s t, an toemesst
g,eo  eonm to buie, ant it, don't aoum tr ben  e to  chem to don'ent aond and won', assium'them tonks and tos , dut eusher to sh them to don' con thement ess it   s p, an toeme sn
gmeou eand wh bui , ant it, dor't aoum tr len  e to   her th bol'ect waod and won't ansiun them tonks and tos , but euther th ch them to bon' cor the end ens it  ns p, an themehst
gmeou eand wh bui d ant ip, don', aout tp ley le to  ther to boe'ent wood and won't ansiun them tonk

단어단위 RNN 

In [104]:
sentence = "Repeat is the best medicine for memory".split()
sentence

['Repeat', 'is', 'the', 'best', 'medicine', 'for', 'memory']

In [105]:
vocab = list(set(sentence))
vocab

['memory', 'best', 'is', 'for', 'Repeat', 'the', 'medicine']

In [109]:
# int indexing 

word2index = {tkn: i for i,tkn in enumerate(vocab, 1)} # unk 토큰 구분위해 
word2index['<UNK>'] = 0
word2index

{'memory': 1,
 'best': 2,
 'is': 3,
 'for': 4,
 'Repeat': 5,
 'the': 6,
 'medicine': 7,
 '<UNK>': 0}

In [110]:
word2index['best']

2

In [111]:
# index_to_word
index2word = {v: k for k,v in word2index.items()} # v,k 바꾸기 
index2word # input index, return word 

{1: 'memory',
 2: 'best',
 3: 'is',
 4: 'for',
 5: 'Repeat',
 6: 'the',
 7: 'medicine',
 0: '<UNK>'}

In [118]:
# make input, label data 

def build_data(sentence, word2index):
  print("sentence:", sentence)
  print("word2index:", word2index)

  encoded = [word2index[token] for token in sentence] # int encode to each token 
  print("encoded:", encoded)
  
  input_seq, label_seq = encoded[:-1], encoded[1:] # inputs and labels 
  print("input_seq:", input_seq,",", "label_seq:", label_seq)

  input_seq = torch.LongTensor(input_seq).unsqueeze(0) # tensor씌워주고 
  label_seq = torch.LongTensor(label_seq).unsqueeze(0)
  print("unsqueeze:", input_seq,",", label_seq)
  
  return input_seq, label_seq

In [120]:
X,Y = build_data(sentence,word2index)

sentence: ['Repeat', 'is', 'the', 'best', 'medicine', 'for', 'memory']
word2index: {'memory': 1, 'best': 2, 'is': 3, 'for': 4, 'Repeat': 5, 'the': 6, 'medicine': 7, '<UNK>': 0}
encoded: [5, 3, 6, 2, 7, 4, 1]
input_seq: [5, 3, 6, 2, 7, 4] , label_seq: [3, 6, 2, 7, 4, 1]
unsqueeze: tensor([[5, 3, 6, 2, 7, 4]]) , tensor([[3, 6, 2, 7, 4, 1]])


In [121]:
X,Y

(tensor([[5, 3, 6, 2, 7, 4]]), tensor([[3, 6, 2, 7, 4, 1]]))

In [175]:
# model 

class MyRNN(torch.nn.Module):
  def __init__(self, vocab_size, input_size, hidden_size, batch_first=True):
    super(MyRNN, self).__init__()
    # embedding layer
    self.embedding_layer = torch.nn.Embedding(num_embeddings = vocab_size, 
                                        embedding_dim = input_size)
    
    self.rnn_layer = torch.nn.RNN(input_size, hidden_size, batch_first=batch_first)
    self.linear = torch.nn.Linear(hidden_size, vocab_size)

  def forward(self, x):
    output = self.embedding_layer(X) # embedding layer통과 
    #(batch,seq) -> (batch,seq,emb_dim)

    output, hidden = self.rnn_layer(output) # rnn 통과 
    #(batch,seq,emb_dim) -> output(batch,seq,hidden) / hidden(1,batch,hidden)
    
    output = self.linear(output) # 출력층 통과 
    #(batch,seq,hidden) -> (batch,hidden, vocab_size) 

    return output.view(-1, output.size(2)) # 배치와 시퀀스 합쳐서 일자로 펴기
                                           # (batch*seq , vocab_size)  

In [189]:
test_model = MyRNN(vocab_size, 10, hidden_size, batch_first=True)
output = test_model.embedding_layer(X)
print(X)
print()
print(output.shape)
print()
output, hidden = test_model.rnn_layer(output)
print(output.shape)
print(hidden.shape)
print()
# output = test_model.linear(output)
# print(output)
# print(output.view(-1, output.size(2)))

tensor([[5, 3, 6, 2, 7, 4]])

torch.Size([1, 6, 10])

torch.Size([1, 6, 20])
torch.Size([1, 1, 20])



In [190]:
# params
vocab_size = len(word2index)
input_size = 10 # RNN input_size & embedding_dim 
hidden_size = 20 # RNN hidden_size

# why input_size = 5 ? 

In [191]:
model = MyRNN(vocab_size, input_size, hidden_size, batch_first=True)
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [192]:
output = model(X)
print(output.shape)

torch.Size([6, 8])


In [193]:
decode = lambda y : [index2word.get(x) for x in y]

In [194]:
for epoch in range(10):
  output = model(X)
  loss = criterion(output, Y.view(-1))

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  pred = output.softmax(-1).argmax(-1).tolist() 
  print("Epoch: {}, loss: {:.4f}, pred: {}".format(
      epoch, loss, decode(pred)
  ))

Epoch: 0, loss: 1.9611, pred: ['best', 'memory', '<UNK>', 'Repeat', 'Repeat', 'memory']
Epoch: 1, loss: 0.8124, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 2, loss: 0.2448, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 3, loss: 0.0610, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 4, loss: 0.0176, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 5, loss: 0.0065, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 6, loss: 0.0028, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 7, loss: 0.0014, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 8, loss: 0.0007, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
Epoch: 9, loss: 0.0004, pred: ['is', 'the', 'best', 'medicine', 'for', 'memory']
