<a href="https://colab.research.google.com/github/tommyEzreal/study_low_level/blob/main/pytorch/%EB%AA%A8%EB%91%90%EB%A5%BC%EC%9C%84%ED%95%9C%EB%94%A5%EB%9F%AC%EB%8B%9D2/tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 모두를 위한 딥러닝 시즌2 

## pytorch basic tensor manipulation 

  - vector , matrix, tensor

In [1]:
import numpy as np
import torch

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
# rank of t, shape of t
t.ndim, t.shape

(1, (7,))

In [5]:
# 2d array 
t = np.array([[1,2,3],[4,5,6,],[7,8,9]])
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# with torch

t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [15]:
t.dim(), t.shape, t.size()

(1, torch.Size([7]), torch.Size([7]))

In [17]:
t = torch.FloatTensor([[1,2,3],[4,5,6,],[7,8,9]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [18]:
t.dim(), t.shape, t.size()

(2, torch.Size([3, 3]), torch.Size([3, 3]))

In [26]:
# slicing 2d tensor 

t[-1],t[0,1], t[:,1], t[:,:1]

(tensor([7., 8., 9.]), tensor(2.), tensor([2., 5., 8.]), tensor([[1.],
         [4.],
         [7.]]))

In [30]:
# Broadcasting 

m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

m1+m2

tensor([[5., 5.]])

In [31]:
m3 = torch.FloatTensor([3])
m1+m3 # 3 -> [3,3]

tensor([[6., 6.]])

In [33]:
m4 = torch.FloatTensor([[3],[4]])
m1+m4

tensor([[6., 6.],
        [7., 7.]])

In [41]:
# multiplication vs matmul 

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])


print("element wise multiplication:")
print(m1 * m2 ) # or mul()

print("matmul:") 
print(m1.matmul(m2)) # inner product 

element wise multiplication:
tensor([[1., 2.],
        [6., 8.]])
matmul:
tensor([[ 5.],
        [11.]])


In [47]:
# mean 

t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print()
print(t.mean())
print(t.mean(dim=0)) # dim=0 (2x2 -> 1x2)  # axis=0
print(t.mean(dim=1)) # dim=1 => (2x2 -> 2x1) # axis=1
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [50]:
# max and argmax 

t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [51]:
t.max()

tensor(4.)

In [54]:
print(t.max(dim=0)) # axis = 0 
print()
print("max:",t.max(dim=0)[0])
print("argmax:",t.max(dim=0)[1]) # max값의 argument 

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

max: tensor([3., 4.])
argmax: tensor([1, 1])


In [100]:
# View (Reshape)

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
ft.shape


torch.Size([2, 2, 3])

In [110]:
ft.view([-1,4]), ft.view([-1,4]).shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]), torch.Size([3, 4]))

In [119]:
ft.view([-1,4,3]) , ft.view([-1,4,3]).shape

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.]]]), torch.Size([1, 4, 3]))

In [120]:
# squeeze 
# element 개수가 1개인 dim을 없애주는 

ft = torch.FloatTensor([[0],[1],[2]])
ft, ft.shape

(tensor([[0.],
         [1.],
         [2.]]), torch.Size([3, 1]))

In [121]:
print(ft.squeeze(dim=0)) # dim0 = 3 
print(ft.squeeze(dim=1)) # dim1 = 1

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


In [127]:
# unsqueeze
print(ft.squeeze())
print(ft.squeeze().unsqueeze(0))
print(ft.squeeze().unsqueeze(1))
print(ft.squeeze().unsqueeze(-1))

tensor([0., 1., 2.])
tensor([[0., 1., 2.]])
tensor([[0.],
        [1.],
        [2.]])
tensor([[0.],
        [1.],
        [2.]])


In [128]:
# Type Casting 

lt = torch.LongTensor([1,2,3,4])
print(lt)

print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [130]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [133]:
# Concatenate

x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(x)
print(y)
print()
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [134]:
# stacking 

x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1)) 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [137]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0),z.unsqueeze(0)], dim=0))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0),z.unsqueeze(0)], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4., 2., 5., 3., 6.]])


In [152]:
# Ones and Zeros 

x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print()
print(torch.ones_like(x))
print(torch.zeros_like(x))


tensor([[0., 1., 2.],
        [2., 1., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [154]:
# In-Place Operation 

x = torch.FloatTensor([[1,2],[3,4]])

print(x.mul(2.))
print(x)
print()
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
